# Generated by Django 2.0 on 2019-09-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosimapp', '0002_auto_20190907_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='notebookdb',
            fields=[
                ('article_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('content', models.TextField()),
                ('publish_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
