# Generated by Django 2.0 on 2019-12-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cosimapp', '0004_recordmesgdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='recordquestiondb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtitle', models.TextField()),
                ('qcontent', models.TextField()),
            ],
        ),
    ]
